version: '3.1'

services:
  db:
    image: postgres:15.4-alpine
    restart: always
    ports:
      - "5400:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: diego123
      POSTGRES_DB: balance-sales-db