spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  cloud:
    loadbalancer:
      ribbon:
        enable: false
  profiles:
    active: ${ACTIVE_PROFILE}

logging:
  level:
    cl.diego.balance: INFO
---
spring:
  config:
    activate:
      on-profile: prod

balance-sales:
  config:
    customer:
      endpoint: ${CUSTOMER_ENDPOINT}
    service: ONE

---
spring:
  config:
    activate:
      on-profile: test

balance-sales:
  config:
    customer:
      endpoint: http://localhost:8080/test-endpoint
    service: TWO