spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  cloud:
    loadbalancer:
      ribbon:
        enable: false

balance-sales:
  config:
    customer:
      endpoint: ${CUSTOMER_ENDPOINT}